const ProgressionLibrary = [
  {
    id: "D01",
    name: "Axis: tonic opening",
    progression: "I–V–vi–IV",
    tags: ["open", "uplifting"],
    source: "https://openmusictheory.github.io/popRockHarmony.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D02",
    name: "Axis: relative-minor opening",
    progression: "vi–IV–I–V",
    tags: ["bittersweet", "anthemic"],
    source: "https://openmusictheory.github.io/popRockHarmony.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D03",
    name: "Axis: subdominant opening",
    progression: "IV–I–V–vi",
    tags: ["anticipatory", "unresolved"],
    source: "https://openmusictheory.github.io/popRockHarmony.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D04",
    name: "Axis: minor-tonic interpretation",
    progression: "i–bVI–bIII–bVII",
    tags: ["expansive", "emotional"],
    source: "https://openmusictheory.github.io/popRockHarmony.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D05",
    name: "Doo-wop",
    progression: "I–vi–IV–V",
    tags: ["warm", "nostalgic"],
    source: "https://openmusictheory.github.io/popRockHarmony-dooWop.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D06",
    name: "Pachelbel: full",
    progression: "I–V–vi–iii–IV–I–IV–V",
    tags: ["sweeping", "unfolding"],
    source: "https://openmusictheory.github.io/popRockHarmony-pachelbel.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D07",
    name: "Pachelbel: opening fragment",
    progression: "I–V–vi–iii",
    tags: ["reflective", "suspended"],
    source: "https://openmusictheory.github.io/popRockHarmony-pachelbel.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D08",
    name: "Minor lament descent",
    progression: "i–bVII–bVI–V",
    tags: ["dramatic", "tense"],
    source: "https://openmusictheory.github.io/popRockHarmony-lament.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D09",
    name: "Minor descending fifths",
    progression: "i–iv–bVII–bIII",
    tags: ["journey", "release"],
    source: "https://openmusictheory.github.io/popRockHarmony-fifths.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D10",
    name: "Extended minor fifths",
    progression: "i–iv–bVII–bIII–bVI–ii°–V",
    tags: ["sweeping", "purposeful"],
    source: "https://openmusictheory.github.io/popRockHarmony-fifths.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D11",
    name: "Plagal shuttle",
    progression: "I–IV",
    tags: ["spacious", "grounded"],
    source: "https://openmusictheory.github.io/popRockHarmony-plagal.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D12",
    name: "Double plagal",
    progression: "bVII–IV–I",
    tags: ["broad", "triumphant"],
    source: "https://openmusictheory.github.io/popRockHarmony-plagal.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D13",
    name: "Extended plagal",
    progression: "bVI–bIII–bVII–IV–I",
    tags: ["expanding", "bold"],
    source: "https://openmusictheory.github.io/popRockHarmony-plagal.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D14",
    name: "Functional arrival",
    progression: "ii–V–I",
    tags: ["settled", "satisfying"],
    source:
      "https://musictheory.pugetsound.edu/mt21c/ShorterProgressionsFromTheCircleOfFifths.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D15",
    name: "Turnaround",
    progression: "I–vi–ii–V",
    tags: ["warm", "flowing"],
    source:
      "https://musictheory.pugetsound.edu/mt21c/ShorterProgressionsFromTheCircleOfFifths.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D16",
    name: "Fifths chain",
    progression: "iii–vi–ii–V",
    tags: ["rolling", "expectant"],
    source:
      "https://musictheory.pugetsound.edu/mt21c/ShorterProgressionsFromTheCircleOfFifths.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D17",
    name: "Fifths chain rotation",
    progression: "ii–V–iii–vi",
    tags: ["buoyant", "circling"],
    source:
      "https://musictheory.pugetsound.edu/mt21c/ShorterProgressionsFromTheCircleOfFifths.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "D18",
    name: "Minor wave",
    progression: "i–bVII–bVI–bVII",
    tags: ["brooding", "driving"],
    source: "https://musictheory.pugetsound.edu/mt21c/i-VII-VI-VII.html",
    detail: "Documented harmonic pattern; mood tags are editorial.",
    evidence: "Documented",
  },
  {
    id: "V01",
    name: "Rising horizon",
    progression: "i–bVI–bVII",
    tags: ["anticipation", "lift"],
    source: "",
    detail: "Two major chords climbing back toward minor home",
    evidence: "Variation",
  },
  {
    id: "V02",
    name: "Dark return",
    progression: "i–bVI–iv–V",
    tags: ["drama", "urgency"],
    source: "",
    detail: "Major V pulling back to minor tonic",
    evidence: "Variation",
  },
  {
    id: "V03",
    name: "Softer return",
    progression: "i–bVI–iv–v",
    tags: ["melancholy", "floating"],
    source: "",
    detail: "Compare directly with V02; only V becomes v",
    evidence: "Variation",
  },
  {
    id: "V04",
    name: "Minor lift",
    progression: "i–iv–bVI–bVII",
    tags: ["expansive", "searching"],
    source: "",
    detail: "Minor opening broadens into major chords",
    evidence: "Variation",
  },
  {
    id: "V05",
    name: "Open ascent",
    progression: "bVI–bVII–i–i",
    tags: ["build", "arrival"],
    source: "",
    detail: "Extra time on the tonic after the ascent",
    evidence: "Variation",
  },
  {
    id: "V06",
    name: "Aeolian space",
    progression: "i–bVI",
    tags: ["atmospheric", "intimate"],
    source: "",
    detail: "Two-chord canvas with shared chord tones",
    evidence: "Variation",
  },
  {
    id: "V07",
    name: "Dorian light",
    progression: "i–IV",
    tags: ["hopeful", "mysterious"],
    source: "",
    detail: "Major IV introduces the natural sixth",
    evidence: "Variation",
  },
  {
    id: "V08",
    name: "Phrygian edge",
    progression: "i–bII",
    tags: ["ominous", "close"],
    source: "",
    detail: "Semitone root contrast",
    evidence: "Variation",
  },
  {
    id: "V09",
    name: "Minor shadow in major",
    progression: "I–IV–iv–I",
    tags: ["tender", "bittersweet"],
    source: "",
    detail: "One note drops as IV becomes iv",
    evidence: "Variation",
  },
  {
    id: "V10",
    name: "Borrowed arrival",
    progression: "bVI–bVII–I",
    tags: ["bright release", "grandeur"],
    source: "",
    detail: "Major tonic after two borrowed major chords",
    evidence: "Variation",
  },
  {
    id: "V11",
    name: "Chromatic doorway",
    progression: "i–bvi",
    tags: ["uncanny", "cinematic"],
    source: "",
    detail: "Parallel minor triads separated by a major third downward",
    evidence: "Variation",
  },
  {
    id: "V12",
    name: "Seventh-colored turnaround",
    progression: "Imaj7–vi7–ii7–V7",
    tags: ["warm", "mellow"],
    source: "",
    detail: "Compare with D15's triads at the same tempo",
    evidence: "Variation",
  },
  {
    id: "U01",
    name: "Courageous",
    progression: "i–bIII–bVII–iv",
    tags: ["epic", "courageous"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=242s",
    detail:
      "Kevin Kuschel’s cinematic pattern 1. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "Minor opening → bright middle → serious return.",
  },
  {
    id: "U02",
    name: "Unstoppable",
    progression: "i–bIII–bVI–iv",
    tags: ["epic", "determined"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=335s",
    detail:
      "Kevin Kuschel’s cinematic pattern 2. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "Forward motion with a reflective minor ending.",
  },
  {
    id: "K03",
    name: "Hopeful",
    progression: "i–v–bVII–IV",
    tags: ["hopeful", "lift"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=471s",
    detail:
      "Kevin Kuschel’s cinematic pattern 3. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "Two minor chords open into major IV.",
  },
  {
    id: "K04",
    name: "Lonely",
    progression: "bVI–bVII–i–bVII",
    tags: ["lonely", "atmospheric"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=591s",
    detail:
      "Kevin Kuschel’s cinematic pattern 4. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "Climb toward home, then fall back into the loop.",
  },
  {
    id: "K05",
    name: "Honorable",
    progression: "iv–bVII–i–bVI",
    tags: ["noble", "bittersweet"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=754s",
    detail:
      "Kevin Kuschel’s cinematic pattern 5. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "A bright turn surrounded by minor harmony.",
  },
  {
    id: "K06",
    name: "Superhero",
    progression: "i–bVI–IV–bVI–bVII",
    tags: ["bold", "epic"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=886s",
    detail:
      "Kevin Kuschel’s cinematic pattern 6. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "A chromatic inner voice builds toward a bold return.",
  },
  {
    id: "K07",
    name: "Love",
    progression: "I–ivadd6–I",
    tags: ["tender", "warm"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=996s",
    detail:
      "Kevin Kuschel’s cinematic pattern 7. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "Borrowed minor color creates tension before home.",
  },
  {
    id: "K08",
    name: "Uplifting",
    progression: "I–bVI–bVII–iv",
    tags: ["uplifting", "triumphant"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=1043s",
    detail:
      "Kevin Kuschel’s cinematic pattern 8. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "Three major chords, then a minor shadow.",
  },
  {
    id: "K09",
    name: "Dark dramatic",
    progression: "i–bIII–ii°–V–V7/IV–i/bIII–bVI–iv–V",
    tags: ["dark", "dramatic", "tense"],
    source: "https://www.youtube.com/watch?v=OyQNXEBDDYs&t=1129s",
    detail:
      "Kevin Kuschel’s cinematic pattern 9. Feeling labels reflect the creator’s interpretation; playback uses your chosen beats per chord.",
    evidence: "Video reference",
    collection: "cinematic",
    arc: "Diminished tension → descending bass → dominant return.",
  },
];
